# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
