# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20170315_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
