# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driver_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
