# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_driver_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='zones',
        ),
        migrations.AddField(
            model_name='zone',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Driver'),
        ),
    ]
