# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0011_auto_20170405_1041'),
        ('driver', '0011_remove_driver_isbusy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverFare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.Passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(blank=True, max_length=100, null=True)),
                ('dropoff', models.CharField(blank=True, max_length=100, null=True)),
                ('seats', models.IntegerField(null=True)),
                ('over', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
                ('passengerName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passenger.Passenger')),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, max_length=100, null=True)),
                ('end', models.CharField(blank=True, max_length=100, null=True)),
                ('pickupLoc', models.CharField(blank=True, max_length=100, null=True)),
                ('seats', models.IntegerField(null=True)),
                ('over', models.BooleanField(default=False)),
                ('assignedDriver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passenger.Passenger')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='request',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='request',
            name='passenger',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
