# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_auto_20170405_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='assignedDriver',
            new_name='assigneddriver',
        ),
        migrations.RenameField(
            model_name='riderequest',
            old_name='pickupLoc',
            new_name='pickuploc',
        ),
    ]
