# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0013_auto_20170405_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='assigneddriver',
            new_name='driver',
        ),
    ]
