# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='zones',
            field=models.ManyToManyField(null=True, to='passenger.Zone'),
        ),
    ]
