# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_auto_20170316_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
