# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0004_passenger_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='zones',
        ),
    ]
