# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0005_remove_passenger_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passenger.Passenger'),
        ),
    ]
