# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0009_riderequest_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='passenger',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
