# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0010_auto_20170403_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='passenger',
        ),
        migrations.DeleteModel(
            name='RideRequest',
        ),
    ]
