# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ratings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0005_driver_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', ratings.models.IntegerRangeField()),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.Rating')),
            ],
        ),
    ]
